workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build 

run_unit_test:
    stage: test
    image: node:20-alpine3.14
    tags:
      - ec2
      - docker
      - remote
    before_script:
      - cd app
      - npm install
    script:
      - npm test
    artifacts:
      when: always
      paths:
        - app/junit.xml
      reports:
        junit: app/junit.html

build_image:
    stage: build
    tags:
      - ec2
      - shell
      - remote
    script:
      - docker build -t registry.gitlab.com/fdat3/node-cicd:1.0 .

push_image:
    stage: build    
    needs:
      - build_image
    tags:
      - ec2
      - shell 
      - remote 
    before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    script:
      - docker push registry.gitlab.com/fdat3/node-cicd
    